Crud-alumnos/Crud-alumnos/Models/Alumno.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_alumnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int Edad { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int CodCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}

Crud-alumnos/Crud-alumnos/Controllers/AlumnosController.cs
using Crud_alumnos.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Crud_alumnos.Controllers
{
    public class AlumnosController : Controller
    {
        // GET: Alumnos
        public ActionResult Index()
        {
            try
            {
                //int edad = 18;

                //string sql = @"select a.Id, a.Nombres, a.Apellidos, a.Edad, a.Sexo, a.FechaRegistro, c.Nombre as NombreCiudad
                //           from Alumno a inner join Ciudad c on a.CodCiudad = c.Id where a.Edad > @edadAlumno";

                using (var db = new AlumnosContext())
                {



                    //usando linq para mapar alumnoce y obtener sus datos
                     var data = from a in db.Alumno
                                join c in db.Ciudad on a.CodCiudad  equals c.id
                                select new AlumnoCE() {

                                    Id = a.Id,
                                    Nombres = a.Nombres,
                                    Apellidos = a.Apellidos,
                                    Edad = a.Edad,
                                    Sexo = a.Sexo,
                                    NombreCiudad = c.Nombre,
                                    FechaRegistro = a.FechaRegistro

                                };

                     //usando linkiu de identity framework con expreciones lamda
                     List<Alumno> lista = db.Alumno.Where(a => a.Edad > 18).ToList();
                     //return View(db.Alumno.ToList());
                     return View(data.ToList());


                    //return View(db.Database.SqlQuery<AlumnoCE>(sql).ToList());

                    //return View(db.Database.SqlQuery<AlumnoCE>(sql, new SqlParameter("@edadAlumno", edad)).ToList());
                }
            }
            catch (Exception)
            {

                throw;
            }


            //conexion
            //AlumnosContext db = new AlumnosContext();

            //usar linkiu de identiti framework
            //db.Alumno.ToList();
            //crea una lista con los alumnos mayores a 18
            //List<Alumno> lista = db.Alumno.Where(a => a.Edad > 18).ToList(); 

            // return View(db.Alumno.ToList()); //envia todos los alumnos como una lista
            //return View(db.Alumno.ToList)
        }

        public ActionResult Agregar()
        {

            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(Alumno a)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }


            try
            {

                using (var db = new AlumnosContext())
                {
                    a.FechaRegistro = DateTime.Now;
                    db.Alumno.Add(a);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {

                ModelState.AddModelError(" ", "error al agregar el alumno - " + ex.Message);
                return View();
            }


        }


        public ActionResult Agregar2() {
            return View();
        }


        public ActionResult ListaCiudades() {

            using (var db = new AlumnosContext()) {

                return PartialView(db.Ciudad.ToList());
            }
        
        }

        public ActionResult Editar(int id)
        {

            

            try
            {
                using (var db = new AlumnosContext())
                {

                    //Alumno al = db.Alumno.Where(a => a.Id == id).FirstOrDefault(); funciona en todos los casos
                    Alumno alu = db.Alumno.Find(id);// no funciona con dos claves primarias iguales
                    return View(alu);
                }
            }
            catch (Exception ex)
            {

                throw;
            }




        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Alumno a)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View();

                using (var db = new AlumnosContext())
                {

                    Alumno al = db.Alumno.Find(a.Id);
                    al.Nombres = a.Nombres;
                    al.Apellidos = a.Apellidos;
                    al.Edad = a.Edad;
                    al.Sexo = a.Sexo;
                    

                    db.SaveChanges();

                    return RedirectToAction("Index");

                }
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public ActionResult Detallesalumno(int id)
        {

            using (var db = new AlumnosContext())
            {
                Alumno alu = db.Alumno.Find(id);
                return View(alu);
            }

        }


        public ActionResult EliminarAlumno(int id)
        {

            using (var db = new AlumnosContext())
            {
                Alumno alu = db.Alumno.Find(id);
                db.Alumno.Remove(alu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

        }


        public static string NombreCiudad(int CodCiudad) {
            using (var db = new AlumnosContext()) {
                return db.Ciudad.Find(CodCiudad).Nombre;
            }
        }




    }
}

Crud-alumnos/Crud-alumnos/Views/Alumnos/Agregar.cshtml
@model Crud_alumnos.Models.Alumno

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <select class="form-control" id="Sexo" name="Sexo">
                    <option value="F">Femenino</option>
                    <option value="M">Masculino</option>
                </select>

               
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodCiudad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("ListaCiudades", "Alumnos")

                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("REgresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Crud-alumnos/Crud-alumnos/Views/Alumnos/Agregar2.cshtml
@model Crud_alumnos.Models.Alumno

@{
    ViewBag.Title = "Agregar2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar2</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaRegistro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaRegistro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaRegistro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodCiudad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodCiudad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodCiudad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Crud-alumnos/Crud-alumnos/Views/Alumnos/Detallesalumno.cshtml
@model Crud_alumnos.Models.Alumno

@{
    ViewBag.Title = "Detallesalumno";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detallesalumno</h2>

<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre completo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>

             
        <dt>
            Edad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            Sexo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
           Fecha registro
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Editar", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Crud-alumnos/Crud-alumnos/Views/Alumnos/Editar.cshtml
@model Crud_alumnos.Models.Alumno

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control" id="Sexo" name="Sexo">
                    <option value="F" @(Model.Sexo == "F" ? "selected" : "")>Femenino</option>
                    <option value="M" @(Model.Sexo == "M" ? "selected" : "")>Masculino</option>
                </select>
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodCiudad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("ListaCiudades", "Alumnos")

                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script>

        $("#CodCiudad").val("@Model.CodCiudad");

    </script>

}

Crud-alumnos/Crud-alumnos/Views/Alumnos/Index.cshtml
@model IEnumerable<Crud_alumnos.Models.AlumnoCE>

@{
    ViewBag.Title = "Lista de alumnos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>lista de alumnos</h2>

<p>
    @Html.ActionLink("Crear nuevo", "Agregar")
</p>
<table class="table">
    <tr>
        <th>
            <!--Html.DisplayNameFor(model => model.Nombres)  agregar el arroba antes-->
            Nombre completo
        </th>
        <th>
            <!--Html.DisplayNameFor(model => model.Apellidos)-->
            Apellido
        </th>
        <th>
            <!--Html.DisplayNameFor(model => model.Edad)-->
            Edad
        </th>
        <th>
            <!--Html.DisplayNameFor(model => model.Sexo)-->
            Sexo
        </th>
        <th>
            Ciudad
        </th>
        <th>
            <!--Html.DisplayNameFor(model => model.FechaRegistro)-->
            Fecha Alta
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCompleto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @{
                    if (item.Sexo == "m")
                    {
                        <span>masculino</span>
                    }
                    else
                    {

                        <span>femenino</span>
                    }


                    @Html.DisplayFor(modelItem => item.Sexo)
                }
            </td>
            <td>
                <!--Crud_alumnos.Controllers.AlumnosController.NombreCiudad(item.CodCiudad) poner arroba-->
                @item.NombreCiudad
            </td>
            <td>
                @item.FechaRegistro.ToString();

                @Html.DisplayFor(modelItem => item.FechaRegistro)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Detallesalumno", new { id = item.Id }) |
                @Html.ActionLink("Eliminar", "EliminarAlumno", new { id = item.Id }, new { @class = "aElimina" })
            </td>
        </tr>
    }

</table>

<!-- poner arroba aqui section script{ -->
<!--<script>

    /*$(".aElimina").click(function (event) {

        if (!confirm("estas seguro de eliminar?")) {

            event.preventDefault();

        }

    });*/

</script>-->

Crud-alumnos/Crud-alumnos/Views/Alumnos/ListaCiudades.cshtml
@model IEnumerable<Crud_alumnos.Models.Ciudad>


    <select class="form-control" id="CodCiudad" name="CodCiudad">


        @foreach (var item in Model)
        {
            <option value="@item.id">@item.Nombre</option>
        }


    </select>